### ISSUE TITLE
It looks like you have a variable "opts" in at \tasks\css.js:17 that is throwing errors

### ISSUE THREAD

**Issue by che-wf** [dielduarte/slush-angular-basic#3]
When running `gulp` command, I'm getting an error at `\tasks\css.js:17:21` which is throwing the rest of the sequence off.

**Comment by dielduarte** [comment]
hi @jbcoder, there is this error i'm sorry.
I can solve later today ok? 

thanks for your issue =)

**Comment by dielduarte** [comment]
@jbcoder , I solved the error .

Please update your version to the new version (0.0.6)  ok ?

thanks!
